title: "Excel with Eddie"
email: "hello@excelwitheddie.com"
description: "Personalized Microsoft Excel tutoring — formulas, PivotTables, dashboards, automation."

# Site URL (MUST match your custom domain)
url: "https://excelwitheddie.com"

# GitHub Pages setting — always leave empty for root site
baseurl: ""

logo: /assets/images/logo.png


theme: null

plugins:
  - jekyll-seo-tag

# Allows future-dated blog posts to appear
future: true
