title: "Excel with Eddie"
email: "eddie@excelwitheddie.com"
description: "Personalized Microsoft Excel tutoring — formulas, PivotTables, dashboards, automation."

# Site URL (must match your custom domain)
url: "https://excelwitheddie.com"

# GitHub Pages setting — leave empty for root site
baseurl: ""

# You are using custom layouts, so theme must be null
theme: null

logo: /assets/images/logo.png

plugins:
  - jekyll-seo-tag

# Allow Jekyll to serve JS files from this folder
include:
  - assets/js
  - assets/css
  - assets/images
  - assets/icons

# Allows future-dated blog posts to appear
future: true
